### ISSUE TITLE
How to add a field of type "union"?

### ISSUE THREAD

**Issue by JasmineLG** [Talend/avro-schema-editor#15]
Hello again, could you please let me know how to add a field of type "union"?  Thanks!

**Comment by timbault** [comment]
Hi,

the way to add an union field is the same as for the other types: select a field, right click, choose "Add" action and then choose "Choice" (the type union is called "Choice" as an union can be seen as a choice between several types).
When you create an union node it contains by default only one child (a "string" primitive type).
If you want to add more types in an union, same way: select the "choice" node, right click, choose "add" action and select the type you want to add. In case of primitive type, you have to set the needed type in the properties tab.
Restriction on "choice" type are implemented, i.e. "Unions may not contain more than one schema with the same type, except for the named types record, fixed and enum".

Regards,

Tony
